package com.f1soft.campaign.common.constant;

public class MsgConstant {

    public static final String REQUEST_FAILED = "REQUEST_FAILED";
    public static final String OTP_INVALID = "OTP_INVALID";
    public static final String INVALID_CODE = "INVALID_CODE";
    public static final String INVALID_USERNAME_PASSWORD = "INVALID_USERNAME_PASSWORD";
    public static final String INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR";
    public static final String DATA_VALIDATION_ERROR = "";
    public static final String TOKEN_NOT_FOUND = "TOKEN_NOT_FOUND";
    public static final String INVALID_DATA = "INVALID_DATA";
    public static final String INVALID_LOGIN_TOKEN = "INVALID_LOGIN_TOKEN";
    public static final String INVALID_AMOUNT = "INVALID_AMOUNT";
    public static final String INVALID_OFFER_AMOUNT = "INVALID_OFFER_AMOUNT";

    public static final String USERNAME_ALREADY_EXIST = "USERNAME_ALREADY_EXIST";
    public static final String PROMO_CODE_ALREADY_EXIST = "PROMO_CODE_ALREADY_EXIST";
    public static final String CAMPAIGN_EXPIRED = "CAMPAIGN_EXPIRED";
    public static final String CAMPAIGN_COMPLETED = "CAMPAIGN_COMPLETED";
    public static final String CAMPAIGN_AMOUNT_MISMATCH = "CAMPAIGN_AMOUNT_MISMATCH";
    public static final String QUERY_ALREADY_EXISTS = "QUERY_ALREADY_EXISTS";

    public static final String GIFT_CARD_ALREADY_EXIST = "GIFT_CARD_ALREADY_EXIST";
    public static final String GIFT_CARD_PROVIDER_ALREADY_EXIST = "GIFT_CARD_PROVIDER_ALREADY_EXIST";

    public static final String DATABASE_CONNECTION_ESTABLISHED = "DATABASE_CONNECTION_ESTABLISHED";
    public static final String DATABASE_CONNECTION_FAILED = "DATABASE_CONNECTION_FAILED";

    public interface Data {
        String SUCCESS = "SUCCESS";
        String CREATE_SUCCESS = "CREATE_SUCCESS";
        String MODIFY_SUCCESS = "MODIFY_SUCCESS";
        String FAILED = "FAILED";
        String NOT_FOUND = "DATA_NOT_FOUND";
        String CAMPAIGN_CREATE_SUCCESS = "CAMPAIGN_CREATE_SUCCESS";
        String CAMPAIGN_MODIFY_SUCCESS = "CAMPAIGN_MODIFY_SUCCESS";
        String STATUS_CHANGE_SUCCESS = "STATUS_CHANGE_SUCCESS";
        String CAMPAIGN_DELETE_SUCCESS = "CAMPAIGN_DELETE_SUCCESS";

        String GIFT_CARD_CREATE_SUCCESS = "GIFT_CARD_CREATE_SUCCESS";
        String GIFT_CARD_MODIFY_SUCCESS = "GIFT_CARD_MODIFY_SUCCESS";
        String GIFT_CARD_DELETE_SUCCESS = "GIFT_CARD_DELETE_SUCCESS";
        String GIFT_CARD_PROVIDER_CREATE_SUCCESS = "GIFT_CARD_PROVIDER_CREATE_SUCCESS";

        String CUSTOM_QUERY_CREATE_SUCCESS = "CUSTOM_QUERY_CREATE_SUCCESS";
        String CUSTOM_QUERY_MODIFY_SUCCESS = "CUSTOM_QUERY_MODIFY_SUCCESS";

        String CUSTOM_CONNECTION_CREATE_SUCCESS = "CUSTOM_CONNECTION_CREATE_SUCCESS";
        String CUSTOM_CONNECTION_MODIFY_SUCCESS = "CUSTOM_CONNECTION_MODIFY_SUCCESS";
    }

    public interface Date {
        String INVALID_DATE = "INVALID_DATE";
        String SAME_DATE = "SAME_DATE";
    }


    public interface Admin {
        String LOGIN_BRANCH_BLOCKED = "LOGIN_BRANCH_BLOCKED";
        String ALREADY_LOGGEDIN = "ALREADY_LOGGEDIN";
        String LOGIN_BLOCKED = "LOGIN_BLOCKED";
        String LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
    }

    public interface Password {
        String INVALID_PASSWORD_LENGTH = "INVALID_PASSWORD_LENGTH";
        String RESTRICT_SAME_PASSWORD = "RESTRICT_SAME_PASSWORD";
        String LOGIN_PASSWORD_UPDATE_SUCCESS = "LOGIN_PASSWORD_UPDATE_SUCCESS";
        String INVALID_PASSWORD_MESSAGE = "INVALID_PASSWORD_MESSAGE";
        String MIN_ALPHA_CHARACTER = "MIN_ALPHA_CHARACTER";
        String INVALID_ALPHA_POSITION = "INVALID_ALPHA_POSITION";
        String MIN_NUMERIC_CHARACTER = "MIN_NUMERIC_CHARACTER";
        String INVALID_NUMERIC_POSITION = "INVALID_NUMERIC_POSITION";
        String MIN_SPECIAL_CHARACTER = "MIN_SPECIAL_CHARACTER";
        String INVALID_SPECIAL_CHARACTER_POSITION = "INVALID_SPECIAL_CHARACTER_POSITION";
        String PASSWORD_MODIFY_SUCCESS = "PASSWORD_MODIFY_SUCCESS";
        String PASSWORD_POLICY_NOT_MATCHED = "PASSWORD_POLICY_NOT_MATCHED";
    }

    public interface OTP {
        String OTP_GENERATED_SUCCESSFULLY = "OTP_GENERATED_SUCCESSFULLY";
    }

    public interface Customer {
        String INVALID_PROMO_CODE = "INVALID_PROMO_CODE";
        String INVALID_CHANNEL = "INVALID_CHANNEL";
        String INVALID_SERVICE = "INVALID_SERVICE";
        String INVALID_PROFILE = "INVALID_PROFILE";
        String INVALID_AMOUNT = "INVALID_AMOUNT";
        String CODE_EXPIRED = "CODE_EXPIRED";
        String NO_CODE_AVAILABLE = "NO_CODE_AVAILABLE";
        String CODE_BOOK_SUCCESS = "CODE_BOOK_SUCCESS";
        String CODE_ALREADY_USED = "CODE_ALREADY_USED";
        String TRANSACTION_SUCCESS = "TRANSACTION_SUCCESS";
        String INVALID_DATA = "INVALID_DATA";
        String ALLOWED_NUMBER_CROSSED = "ALLOWED_NUMBER_CROSSED";
        String OFFER_NOT_STARTED = "OFFER_NOT_STARTED";
        String OFFER_ALREADY_ENDED = "OFFER_ALREADY_ENDED";
        String OFFER_QUOTA_EXCEEDED = "OFFER_QUOTA_EXCEEDED";
    }

    public interface Image {
        String INVALID_IMAGE = "INVALID_IMAGE";
        String UPLOAD_IMAGE_FAILED = "UPLOAD_IMAGE_FAILED";
        String UPLOAD_IMAGE_SUCCESS = "UPLOAD_IMAGE_SUCCESS";
        String INVALID_IMAGE_SIZE = "INVALID_IMAGE_SIZE";
    }

    public interface DynamicData {
        String DUPLICATE = "DYNAMIC_DUPLICATE";
    }

    public interface FundTransfer {
        String REFUND_SUCCESS = "REFUND_SUCCESS";
        String REFUND_FAILURE = "REFUND_FAILURE";
    }

    public interface Topup {
        String TOPUP_SUCCESS = "TOPUP_SUCCESS";
        String TOPUP_FAILURE = "TOPUP_FAILURE";
    }

    public interface Datapack {
        String DATAPACK_SUCCESS = "DATAPACK_SUCCESS";
        String DATA_PACK_FAILURE = "DATAPACK_FAILURE";
    }

    public interface FileUpload {
        String FILE_UPLOAD_FAILED = "FILE_UPLOAD_FAILED";
        String FILE_UPLOAD_SUCCESS = "FILE_UPLOAD_SUCCESS";
        String FILE_NOT_FOUND = "FILE_NOT_FOUND";
        String FILE_PROCESSING_EXCEPTION = "FILE_PROCESSING_EXCEPTION";
        String FILE_NAME_REQUIRED = "FILE_NAME_REQUIRED";
        String EMPTY_FILE = "EMPTY_FILE";
    }

    public interface BLI {
        String TEACHER_ALREADY_EXIST = "TEACHER_ALREADY_EXISTS";
        String TEACHER_ALREADY_ASSIGNED = "TEACHER_ALREADY_ASSIGNED";
        String TEACHER_REGISTERED_SUCCESS = "TEACHER_REGISTERED_SUCCESS";
    }
}
