export enum Roles {
    ADMIN_HOME = 'ADMIN_HOME',
    CAMPAIGN = 'CAMPAIGN_HOME',
    TRANSACTION = 'TRANSACTION_HOME',
    REPORT = 'REPORT_HOME',
    REDEEM_OFFER = 'REDEEM_OFFER_HOME',
    PACKAGE = 'PACKAGE_HOME',
    USER = 'USER_HOME',
    USER_PROFILE = 'USER_PROFILE_HOME',
    SETTINGS = 'SETTINGS',
    CONTACT = 'CONTACT'
}